### ISSUE TITLE
Velodyne Build Error on indigo-devel branch.

### ISSUE THREAD

**Issue by ghost** [OrebroUniversity/perception_oru#1]
Looks like there is a build error associated with Velodyne on the indigo-devel branch.

`In constructor ‘VelodyneBagReader<PointT>::VelodyneBagReader(std::string, std::string, std::string, std::string, std::string, std::string, ros::Duration, tf::StampedTransform*, double, double, double)’:`

`VelodyneBagReader.h:100:17: error: ‘class velodyne_rawdata::RawData’ has no member named ‘setupOffline’ dataParser.setupOffline(calibration_file, velodyne_max_range, velodyne_min_range); `

**Comment by MalcolmMielle** [comment]
This issue should be solved by changing those lines in `ndt_mcl/CMakeLists.txt`:

line 7
```
 -find_package(catkin REQUIRED COMPONENTS ndt_visualisation rosbag tf nav_msgs sensor_msgs geometry_msgs message_filters ndt_map ndt_registration ndt_rviz visualization_msgs tf_conversions eigen_conversions cmake_modules)
 +find_package(catkin REQUIRED COMPONENTS ndt_visualisation rosbag tf nav_msgs sensor_msgs geometry_msgs message_filters ndt_map ndt_registration ndt_rviz visualization_msgs tf_conversions eigen_conversions cmake_modules velodyne_pointcloud velodyne_msgs)
```

line 61 
```  

  add_executable(3d_ndt_mcl_node2 src/3d_ndt_mcl_node2.cpp)
 -target_link_libraries(3d_ndt_mcl_node2 ${PROJECT_NAME} ${Boost_LIBRARIES} ${OPENGL_LIBRARIES} ${catkin_LIBRARIES} velodyne_rawdata) # ${MRPT_LIBS}${LIBXML2_LIBRARIES} ${GLUT_LIBRARIES} ${JPEG_LIBRARIES} )
 +target_link_libraries(3d_ndt_mcl_node2 ${PROJECT_NAME} ${Boost_LIBRARIES} ${OPENGL_LIBRARIES} ${catkin_LIBRARIES}) # ${MRPT_LIBS}${LIBXML2_LIBRARIES} ${GLUT_LIBRARIES} ${JPEG_LIBRARIES} )
  
```

**Comment by ghost** [comment]
Thanks. The same error occurs during ndt_calibration too.
ndt_calibration.dir/src/ndt_calib.cpp

`ndt_offline/VelodyneBagReader.h: In constructor ‘VelodyneBagReader<PointT>::VelodyneBagReader(std::string, std::string, std::string, std::string, std::string, std::string, ros::Duration, tf::StampedTransform*, double, double, double)’:`

`ndt_offline/include/ndt_offline/VelodyneBagReader.h:100:17: error: ‘class velodyne_rawdata::RawData’ has no member named ‘setupOffline’ dataParser.setupOffline(calibration_file, velodyne_max_range, velodyne_min_range);`

I attempted to make an identical change to the ndt_calib CMakeLists.txt. However, the error persisted.

**Comment by ahuer2435** [comment]
Hi Sir,
I encountered a similar problem. when build the error appear:

![error](https://user-images.githubusercontent.com/29789591/34805897-40ccb844-f6bb-11e7-9e96-a47274ce6762.png)

os: ubuntu14.04
ros: indigo
and I installed ros-indigo-velodyne-pointcloud. 
Looking forward to your reply.

**Comment by ahuer2435** [comment]
branch： indigo-devel

**Comment by dan11003** [comment]
Hello,
Did you clone https://github.com/OrebroUniversity/velodyne into your catkin
workspace?
Please let me know if this works.


Med vänliga hälsningar
Best regards
Daniel Adolfsson

2018-01-11 3:57 GMT+01:00 ahuer2435 <notifications@github.com>:

**Comment by ahuer2435** [comment]
@dan11003  I did not clone  https://github.com/OrebroUniversity/velodyne  , I installed ros-indigo-velodyne-pointcloud only. 
Now it is solved by following your guide. Thank you very much.
