### ISSUE TITLE
Datasets for ros tutorial no longer available

### ISSUE THREAD

**Issue by tengfoonglam** [OrebroUniversity/perception_oru#13]
Hi,

I am following the tutorial found http://wiki.ros.org/perception_oru/Tutorials/Using%20NDT%20Fuser%20to%20create%20an%20NDT%20map
and
http://wiki.ros.org/perception_oru/Tutorials/Running%20NDT-MCL%20examples

It seems that the links for the dataset files mapping.bag, localization.bag, 3d_laser_short.bag, as well as the links included in the .sh files ./get_localization_data.sh and ./get_mapping_data.sh are broken.

Would it be possible to fix the download links? Thank you!

**Comment by tengfoonglam** [comment]
I attempted to download today again the links are working fine now, not sure what changed. Thank you and sorry for the inconvenience caused.

**Comment by caolaolao** [comment]
hello I can't access the dataset website either. Do you have any more datasets? Can you share them with me
