### ISSUE TITLE
Dual-Timescale NDT MCL package

### ISSUE THREAD

**Issue by baker-Xie** [OrebroUniversity/perception_oru#14]
This is a great job. But I want to know is there any plan to add the dual-Timescale ndt mcl package ? And is there any plan to update this repo in ros-melodic or ros-noetic?

**Comment by peterzxli** [comment]
I am planning to use this on ros-noetic, and I just noticed that the source code for this project is gone. Are you able to share the source code with me? Thanks!

**Comment by tstoyanov** [comment]
I think the dual-scale code is unfortunately gone beyond recovery. If anyone is interested in re-implementing it, we'd be happy to integrate it here.

For more up-to-date version of the ndt packages check here:
https://gitsvn-nt.oru.se/software/ndt_core_public
https://gitsvn-nt.oru.se/software/ndt_tools_public
