### ISSUE TITLE
Is this package/code maintained ?

### ISSUE THREAD

**Issue by poornimajd** [OrebroUniversity/perception_oru#16]
Hello @tstoyanov @dan11003 
Thank you for the great work.I am planning to implement ndt-mcl.Is the source code given here to be used as a guide or could you specify the link to the more recent version of the code?
Or are there any ros packages to get started with implementing the ndt-amcl for 2d localization,using ndt with amcl,to improve localization.Any suggestion is greatly appreciated.
Is this the place to get started for 2d localalization? -http://wiki.ros.org/perception_oru/Tutorials/Running%20NDT-MCL%20examples 

Awaiting for your early reply.

Thank you

**Comment by ksatyaki** [comment]
Hello, 

This repository is deprecated. But, the code is maintained at https://gitsvn-nt.oru.se/software

Check out ndt_core and ndt_tools over there.

**Comment by poornimajd** [comment]
Thanks a lot for the reply.Thank you for the sources,I will check it out.

**Comment by libing64** [comment]
> Hello,
> 
> This repository is deprecated. But, the code is maintained at https://gitsvn-nt.oru.se/software
> 
> Check out ndt_core and ndt_tools over there.


https://gitsvn-nt.oru.se/software seem to be inaccessible?

**Comment by tstoyanov** [comment]
Please take a look here:
https://gitsvn-nt.oru.se/software/ndt_core_public
https://gitsvn-nt.oru.se/software/ndt_tools_public

These packages are more up-to-date.
