### ISSUE TITLE
any indigo-supprt branch?`

### ISSUE THREAD

**Issue by jeannotes** [OrebroUniversity/perception_oru#3]
Hi, recently I am studying NDT-based localization methods, I install ubuntu 14.04 (ros-indigo), is there any code available any more?

**Comment by MalcolmMielle** [comment]
I'm not sure how up to date you need to be, but the "develop-indigo" branch should do the trick.
Otherwise not much is incompatible between the port-kinetic branch and indigo. Only the visualization since it depends on qt5.

**Comment by jeannotes** [comment]
Well, I got it ,and finally I set up it ok in ubuntu 14.04, But the problem comes, where do I start, cannot understand the source code, hope to get help from you

**Comment by MalcolmMielle** [comment]
You could start up [here](http://wiki.ros.org/perception_oru/Tutorials)

**Comment by jeannotes** [comment]
@MalcolmMielle 
what is difference between perception_oru-release and perception_oru?
and which pakage shou I learn first? the code is a little bit hard for me? 
any suggestions?

**Comment by MalcolmMielle** [comment]
Use perception_oru, the release version is something else. Have you done the tutorials I sent you ?

**Comment by jeannotes** [comment]
@MalcolmMielle 
working on it now, really thank you for kind reply.
as a beginner, hard for me.right now I already understand the NDT-algorithm, hopes to grasp all the software architure and other algorithms.
