### ISSUE TITLE
ndt_mcl examples datasets missing

### ISSUE THREAD

**Issue by SeanGuoXuan** [OrebroUniversity/perception_oru#6]
under folder src/ndt_mcl/data/, there are two scripts to download datasets.
I think the none of those links are working:
http://aass.oru.se/Research/Learning/data/tutorials/mapping.bag
http://aass.oru.se/Research/Learning/data/tutorials/localization.bag
Could someone update pls?

**Comment by SeanGuoXuan** [comment]
sry, I got the right link. close it

**Comment by caolaolao** [comment]
Hello, I have the same problem with you, could you share the correct link with me？
